# -*- coding: UTF-8 -*-
# -----------------------------------------------------------------------------
#    xierpa server
#    Copyright (c) 2014+  buro@petr.com, www.petr.com, www.xierpa.com
#
#    X I E R P A  3  A P P
#    Distribution by the MIT License.
#
# -----------------------------------------------------------------------------
#
#    python setup.py py2app
#
"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['English.lproj', ]
OPTIONS = {'argv_emulation': True }

setup(app=APP, name="Xierpa 3", data_files=DATA_FILES, options={'py2app': OPTIONS}, setup_requires=['py2app'],)
